name: test-linux
on: [push]
jobs:
  cargo-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        database: [mssql-2017, mssql-2019]
        rust: [stable, beta]

    env:
      TIBERIUS_TEST_CONNECTION_STRING: "server=tcp:localhost,1433;user=SA;password=<YourStrong@Passw0rd>;TrustServerCertificate=true"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
      - run: docker-compose -f docker-compose.yml up -d ${{matrix.database}}
      - run: apt install -y openssl libkrb5-dev
      - run: cargo test --features all
