name: test-linux
on: [push]
jobs:
  cargo-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        database: [2017, 2019]
        rust: [stable, beta]
        features:
          - "--features=all"
          - "--no-default-features --features chrono"

    env:
      TIBERIUS_TEST_CONNECTION_STRING: "server=tcp:localhost,1433;user=SA;password=<YourStrong@Passw0rd>;TrustServerCertificate=true"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
      - name: Start SQL Server ${{matrix.database}}
        run: docker-compose -f docker-compose.yml up -d mssql-${{matrix.database}}
      - name: Install dependencies
        run: sudo apt install -y openssl libkrb5-dev
      - name: Run tests
        run: cargo test --features all
