name: test-linux
on: [push]
jobs:
  cargo-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        database:
          - mssql-2017
          - mssql-2019

    env:
      TIBERIUS_TEST_CONNECTION_STRING: "server=tcp:localhost,1433;user=SA;password=<YourStrong@Passw0rd>;TrustServerCertificate=true"

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: docker-compose -f docker-compose.yml up -d ${{matrix.database}}
      - run: nix-shell --run "cargo test"
